# Коллаборативная фильтрация

In [4]:
source("../scripts/utils.r")

rates <- matrix(c(
    10, 8, 5, 7, -1, -1, -1,
    1, 0, 3, 0, 10, 0, -1,
    8, 8, 1, -1, -1, 8, -1,
    1, 10, -1, 7, -1, 6, 10,
    3, 1, 7, -1, -1, 0, 10
), ncol = 7, nrow = 5, byrow = TRUE)

sim <- calculate_sim(rates, target_ind = 1, rated = FALSE)

sim

1,0.09782503,0.6257522,0.4516918,0.2893699


In [5]:
cal_rates <- calibrate_rates(rates, sim)

print(rates)
print(round(cal_rates, 3))

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]   10    8    5    7   -1   -1   -1
[2,]    1    0    3    0   10    0   -1
[3,]    8    8    1   -1   -1    8   -1
[4,]    1   10   -1    7   -1    6   10
[5,]    3    1    7   -1   -1    0   10
       [,1]  [,2]   [,3]   [,4]   [,5]   [,6]   [,7]
[1,] 10.000 8.000  5.000  7.000 -1.000 -1.000 -1.000
[2,]  0.098 0.000  0.293  0.000  0.978  0.000 -0.098
[3,]  5.006 5.006  0.626 -0.626 -0.626  5.006 -0.626
[4,]  0.452 4.517 -0.452  3.162 -0.452  2.710  4.517
[5,]  0.868 0.289  2.026 -0.289 -0.289  0.000  2.894


In [6]:
target_ind <- 1

model <- fit_col_filtering(rates)
pred <- predict_col_filtering(model, target_ind)
print(pred)

     [,1] [,2] [,3] [,4]      [,5]     [,6]     [,7]
[1,]    0    0    0    0 -2.077444 6.716168 2.891166


## Вычисление метрик